import { supabase } from './supabase'
import type { CalendarEventRow, EventType } from '@/types/database.types'

// ── Fetch ─────────────────────────────────────────────────────

export async function getEvents(
  userId:    string,
  startDate?: string,   // ISO string — if omitted, fetch all
  endDate?:   string,
): Promise<CalendarEventRow[]> {
  let query = supabase
    .from('calendar_events')
    .select('*')
    .eq('user_id', userId)
    .order('starts_at', { ascending: true })

  if (startDate) query = query.gte('starts_at', startDate)
  if (endDate)   query = query.lte('starts_at', endDate)

  const { data, error } = await query
  if (error) throw error
  return (data ?? []) as CalendarEventRow[]
}

export async function getEvent(eventId: string): Promise<CalendarEventRow | null> {
  const { data, error } = await supabase
    .from('calendar_events')
    .select('*')
    .eq('id', eventId)
    .maybeSingle()
  if (error) throw error
  return data as CalendarEventRow | null
}

// ── Create ────────────────────────────────────────────────────

export interface CreateEventParams {
  userId:    string
  title:     string
  eventType: EventType
  startsAt:  string       // ISO datetime
  endsAt:    string | null
  notes:     string | null
  groupId:   string | null
}

export async function createEvent(params: CreateEventParams): Promise<CalendarEventRow> {
  const { data, error } = await supabase
    .from('calendar_events')
    .insert({
      user_id:    params.userId,
      title:      params.title,
      event_type: params.eventType,
      starts_at:  params.startsAt,
      ends_at:    params.endsAt,
      notes:      params.notes,
      group_id:   params.groupId,
    })
    .select()
    .single()
  if (error) throw error
  return data as CalendarEventRow
}

// ── Update ────────────────────────────────────────────────────

export interface UpdateEventParams {
  title?:     string
  eventType?: EventType
  startsAt?:  string
  endsAt?:    string | null
  notes?:     string | null
  groupId?:   string | null
}

export async function updateEvent(
  eventId: string,
  updates: UpdateEventParams,
): Promise<CalendarEventRow> {
  const payload: Record<string, unknown> = {}
  if (updates.title     !== undefined) payload.title      = updates.title
  if (updates.eventType !== undefined) payload.event_type = updates.eventType
  if (updates.startsAt  !== undefined) payload.starts_at  = updates.startsAt
  if (updates.endsAt    !== undefined) payload.ends_at    = updates.endsAt
  if (updates.notes     !== undefined) payload.notes      = updates.notes
  if (updates.groupId   !== undefined) payload.group_id   = updates.groupId

  const { data, error } = await supabase
    .from('calendar_events')
    .update(payload)
    .eq('id', eventId)
    .select()
    .single()
  if (error) throw error
  return data as CalendarEventRow
}

// ── Delete ────────────────────────────────────────────────────

export async function deleteEvent(eventId: string): Promise<void> {
  const { error } = await supabase
    .from('calendar_events')
    .delete()
    .eq('id', eventId)
  if (error) throw error
}

// ── Helpers ───────────────────────────────────────────────────

/**
 * Checks whether a calendar event was generated by the AI study planner.
 * Events seeded by plannerService carry notes starting with a duration/type pattern.
 */
export function isAIGeneratedEvent(event: CalendarEventRow): boolean {
  return (
    event.event_type === 'study' &&
    typeof event.notes === 'string' &&
    /\d+ min ·/.test(event.notes)
  )
}

/** Maps EventType to a hex colour for FullCalendar rendering */
export function eventTypeColor(type: EventType): string {
  const map: Record<EventType, string> = {
    exam:       '#ef4444',   // red-500
    assignment: '#f97316',   // orange-500
    study:      '#3b82f6',   // blue-500
    meeting:    '#a855f7',   // purple-500
    reminder:   '#6b7280',   // gray-500
  }
  return map[type] ?? '#6b7280'
}

export const EVENT_TYPE_LABELS: Record<EventType, string> = {
  exam:       'Exam',
  assignment: 'Assignment',
  study:      'Study session',
  meeting:    'Meeting',
  reminder:   'Reminder',
}
